### ISSUE TITLE
reset script does not source environment variables from .env

### ISSUE THREAD

**Issue by ferrao** [academia-de-codigo/noire-server#6]
reset script invokes knex directly and hence does not source environment variables from .env, which may cause unexpected behaviour

**Comment by p-brighenti** [comment]
The `dotenv#config()` method should be invoked as early as possible. Otherwise when loading the `config` module, the environment variables values will be set by the defaults defined in `config.js` before sourcing the contents of the `.env` file. 

Since `dotenv` will not override any environment variable value, this was conflicting with being able to set the any environment variable value to the intended one. 

This issue occurred when the `config` module was required before the first invocation of `dotenv#config()`.

**Comment by p-brighenti** [comment]
Closed in d19f687.
